using Spark.Infrastructure.EventStore;

/* Copyright (c) 2012 Spark Software Ltd.
 * 
 * This source is subject to the GNU Lesser General Public License.
 * See: http://www.gnu.org/copyleft/lesser.html
 * 
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE. 
 */

namespace Spark.Infrastructure.Domain
{
    /// <summary>
    /// The resulting <see cref="Aggregate"/> and <see cref="Commit"/> after successfully invoking <see cref="IStoreAggregates.Save"/>.
    /// </summary>
    public sealed class SaveResult
    {
        /// <summary>
        /// The modified <see cref="Aggregate"/> resulting from invoking <see cref="IStoreAggregates.Save"/>.
        /// </summary>
        public Aggregate Aggregate { get; private set; }

        /// <summary>
        /// The <see cref="Commit"/> generated by invoking <see cref="IStoreAggregates.Save"/>.
        /// </summary>
        public Commit Commit { get; private set; }

        /// <summary>
        /// Initializes a new instance of <see cref="SaveResult"/>.
        /// </summary>
        /// <param name="aggregate">The saved <see cref="Aggregate"/>.</param>
        /// <param name="commit">The generated <see cref="Commit"/></param>
        public SaveResult(Aggregate aggregate, Commit commit)
        {
            Verify.NotNull(aggregate, "aggregate");
            Verify.NotNull(commit, "commit");

            Aggregate = aggregate;
            Commit = commit;
        }
    }
}
